# training template for your executor app
# after build image, it should at /img-man/training-template.yaml

# preserved: gpu_id, task_id, pretrained_model_params, class_names
# gpu_id: '0'
# task_id: 'default-training-task'
# pretrained_model_params: ['/in/models/best.pth']
# class_names: ['person', 'cat']

# format of annotations and images that ymir should provide to this docker container
#   annotation format: must be seg-coco
#   image format: must be raw
export_format: 'seg-coco:raw'

# just for test, remove this key in your own docker image
expected_mIoU: 0.983  # expected mIoU for training task
expected_mAcc: 0.800  # expected mAcc for training task
idle_seconds: 3  # idle seconds for each task
